window.VIZ_RUNS = window.VIZ_RUNS || {};
window.VIZ_RUNS["sample"] = {
  "run_id": "sample",
  "programs": [
    {
      "id": "p0000",
      "parent_id": null,
      "generation": 0,
      "island_idx": 0,
      "combined_score": 0.11,
      "correct": 1,
      "children_count": 2,
      "timestamp": "2026-07-01T08:02:00Z",
      "complexity": 6,
      "patch_name": "Seed: all-H + linear CX ansatz",
      "patch_description": "Baseline hardware-efficient ansatz: a layer of Hadamards for superposition, a linear nearest-neighbor CX chain for entanglement, then a single RY rotation layer per qubit. This is the standard starting point ShinkaEvolve seeds every island with before any LLM-authored patches are applied.",
      "patch_type": "insertion",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Initial program compiles and runs but wins fewer than 15% of games against the minimax opponent. Entanglement pattern is too shallow to capture the board's diagonal correlations.",
      "public_metrics": {
        "win_rate": 0.062,
        "draw_rate": 0.0695,
        "gate_count": 6,
        "circuit_depth": 2,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": "q0: --H--@--------------RY(t0)--Z--\nq1: --H--X--@-----------RY(t1)--Z--\nq2: --H-----X--@--------RY(t2)--Z--\n"
    },
    {
      "id": "p0001",
      "parent_id": "p0000",
      "generation": 4,
      "island_idx": 0,
      "combined_score": 0.18,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-02T12:00:00Z",
      "complexity": 15,
      "patch_name": "Tune RY rotation init range",
      "patch_description": "Narrowed the random initialization range for the RY parameters from [-pi, pi] to [-pi/4, pi/4] to reduce the chance of landing in a barren-plateau region early in training. Small but consistent improvement in win rate.",
      "patch_type": "param_tune",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Small step up. Training curves are less noisy in the first 50 iterations, but the ansatz still can't represent the corner-vs-center asymmetry of the board well.",
      "public_metrics": {
        "win_rate": 0.1889,
        "draw_rate": 0.1418,
        "gate_count": 15,
        "circuit_depth": 4,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0002",
      "parent_id": "p0001",
      "generation": 11,
      "island_idx": 0,
      "combined_score": 0.27,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-04T19:06:00Z",
      "complexity": 36,
      "patch_name": "Switch to ring entanglement",
      "patch_description": "Replaced the linear CX chain with a ring topology (wrap-around CX from the last qubit back to the first). Gives every qubit two entangling neighbors instead of one or two asymmetrically, which should better match the rotational symmetry of a 3x3 board.",
      "patch_type": "refactor",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Meaningful jump in win rate and a visible drop in draw rate. The ring topology seems to let the circuit express moves that are equivalent under 90-degree board rotation with fewer parameters.",
      "public_metrics": {
        "win_rate": 0.2538,
        "draw_rate": 0.0254,
        "gate_count": 36,
        "circuit_depth": 12,
        "param_count": 4
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0003",
      "parent_id": "p0002",
      "generation": 19,
      "island_idx": 0,
      "combined_score": 0.34,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-07T03:50:00Z",
      "complexity": 46,
      "patch_name": "Add second RY layer with fresh params",
      "patch_description": "Inserted a second RY rotation layer (with its own parameter block) after the ring entanglement, effectively doubling ansatz depth. Complexity budget still well within the task's gate-count ceiling.",
      "patch_type": "insertion",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Depth increase pays off, though returns are diminishing relative to the entanglement-pattern change at generation 11. Gate count is creeping up; may need pruning soon.",
      "public_metrics": {
        "win_rate": 0.3304,
        "draw_rate": 0.0248,
        "gate_count": 46,
        "circuit_depth": 15,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": "q0: --H--@--------------RY(t0)--Z--\nq1: --H--X--@-----------RY(t1)--Z--\nq2: --H-----X--@--------RY(t2)--Z--\n"
    },
    {
      "id": "p0004",
      "parent_id": "p0003",
      "generation": 26,
      "island_idx": 0,
      "combined_score": 0.41,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-09T10:35:00Z",
      "complexity": 65,
      "patch_name": "Swap basis gates: CZ instead of CX",
      "patch_description": "Recompiled the ring entangler using CZ gates instead of CX, paired with H gates absorbed into the existing initial layer. Motivated by a text-feedback note from generation 19 flagging that CZ is native on the target simulator backend and avoids an extra basis-gate translation pass that was inflating the effective circuit depth metric.",
      "patch_type": "refactor",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Score keeps climbing steadily. Effective depth after transpilation dropped 18% for the same logical circuit, which the harness's complexity penalty rewards directly. No behavioral regressions on the held-out game set.",
      "public_metrics": {
        "win_rate": 0.3936,
        "draw_rate": 0.1009,
        "gate_count": 65,
        "circuit_depth": 22,
        "param_count": 4
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0005",
      "parent_id": "p0004",
      "generation": 33,
      "island_idx": 0,
      "combined_score": 0.89,
      "correct": 1,
      "children_count": 3,
      "timestamp": "2026-07-12T17:17:00Z",
      "complexity": 71,
      "patch_name": "Full-connectivity CZ ladder + data re-uploading",
      "patch_description": "This is the patch that broke the plateau. Two changes bundled together: (1) replaced the ring entangler with a full all-to-all CZ ladder so every pair of qubits interacts directly in one layer, and (2) added a second data re-uploading block that re-encodes the board state between entangling layers instead of only at the start. The re-uploading trick is standard in the QML literature for boosting expressivity without adding qubits, but earlier patches on this island never combined it with a fully-connected entangler. Together they let the circuit represent the full 3x3 board's win conditions (rows, columns, both diagonals) in a single forward pass instead of approximating them piecewise.",
      "patch_type": "crossover",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Score more than doubled in one generation (0.41 -> 0.89). Win rate against the minimax opponent jumped from 51% to 94% and draw rate collapsed to near zero, meaning the ansatz is now finding forcing lines rather than stalling into draws. This looks like a genuine expressivity phase transition rather than a lucky seed: rerunning the eval with 3 different random seeds for the classical optimizer gives 0.87-0.90 combined score every time. Gate count did rise by about 35%, so the next few generations should probably focus on pruning the CZ ladder down to only the pairs that carry weight, since not all O(n^2) connections are likely to matter equally.",
      "public_metrics": {
        "win_rate": 0.9007,
        "draw_rate": 0.0487,
        "gate_count": 71,
        "circuit_depth": 25,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 380 130\" width=\"380\" height=\"130\" font-family=\"ui-monospace,SFMono-Regular,Menlo,monospace\" font-size=\"11\"><style>.wire{stroke:#7a7a76;stroke-width:1.5}.gate{fill:#ffffff;stroke:#2a78d6;stroke-width:1.5}.gate2{fill:#ffffff;stroke:#4a3aa7;stroke-width:1.5}.lbl{fill:#0b0b0b}.dot{fill:#0b0b0b}</style><line class=\"wire\" x1=\"20\" y1=\"20\" x2=\"360\" y2=\"20\"/><line class=\"wire\" x1=\"20\" y1=\"60\" x2=\"360\" y2=\"60\"/><line class=\"wire\" x1=\"20\" y1=\"100\" x2=\"360\" y2=\"100\"/><text class=\"lbl\" x=\"2\" y=\"24\">q0</text><text class=\"lbl\" x=\"2\" y=\"64\">q1</text><text class=\"lbl\" x=\"2\" y=\"104\">q2</text><rect class=\"gate\" x=\"45\" y=\"6\" width=\"28\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"53\" y=\"24\">H</text><rect class=\"gate\" x=\"45\" y=\"46\" width=\"28\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"53\" y=\"64\">H</text><rect class=\"gate\" x=\"45\" y=\"86\" width=\"28\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"53\" y=\"104\">H</text><line class=\"wire\" x1=\"110\" y1=\"20\" x2=\"110\" y2=\"60\"/><circle class=\"dot\" cx=\"110\" cy=\"20\" r=\"4\"/><circle cx=\"110\" cy=\"60\" r=\"9\" fill=\"none\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><line x1=\"105\" y1=\"60\" x2=\"115\" y2=\"60\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><line x1=\"110\" y1=\"55\" x2=\"110\" y2=\"65\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><line class=\"wire\" x1=\"150\" y1=\"60\" x2=\"150\" y2=\"100\"/><circle class=\"dot\" cx=\"150\" cy=\"60\" r=\"4\"/><circle cx=\"150\" cy=\"100\" r=\"9\" fill=\"none\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><line x1=\"145\" y1=\"100\" x2=\"155\" y2=\"100\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><line x1=\"150\" y1=\"95\" x2=\"150\" y2=\"105\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><line class=\"wire\" x1=\"190\" y1=\"20\" x2=\"190\" y2=\"100\"/><circle class=\"dot\" cx=\"190\" cy=\"20\" r=\"4\"/><circle cx=\"190\" cy=\"100\" r=\"9\" fill=\"none\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><line x1=\"185\" y1=\"100\" x2=\"195\" y2=\"100\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><line x1=\"190\" y1=\"95\" x2=\"190\" y2=\"105\" stroke=\"#0b0b0b\" stroke-width=\"1.5\"/><rect class=\"gate2\" x=\"225\" y=\"6\" width=\"40\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"231\" y=\"24\">RY(\u03b8)</text><rect class=\"gate2\" x=\"225\" y=\"46\" width=\"40\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"231\" y=\"64\">RY(\u03b8)</text><rect class=\"gate2\" x=\"225\" y=\"86\" width=\"40\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"231\" y=\"104\">RY(\u03b8)</text><rect class=\"gate\" x=\"295\" y=\"6\" width=\"28\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"301\" y=\"24\">Z</text><rect class=\"gate\" x=\"295\" y=\"46\" width=\"28\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"301\" y=\"64\">Z</text><rect class=\"gate\" x=\"295\" y=\"86\" width=\"28\" height=\"28\" rx=\"4\"/><text class=\"lbl\" x=\"301\" y=\"104\">Z</text></svg>",
      "circuit_text": null
    },
    {
      "id": "p0006",
      "parent_id": "p0005",
      "generation": 35,
      "island_idx": 0,
      "combined_score": 0.9,
      "correct": 1,
      "children_count": 3,
      "timestamp": "2026-07-12T19:47:00Z",
      "complexity": 80,
      "patch_name": "Prune low-weight CZ pairs",
      "patch_description": "Inspected the trained CZ ladder from generation 33 and removed the two qubit-pairs whose associated rotation-sensitivity (finite-difference score gradient) was below 1e-3. Keeps expressivity, cuts gate count.",
      "patch_type": "pruning",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Score held steady while gate count dropped 22%, confirming the earlier hypothesis that not all all-to-all connections were pulling weight. Good complexity/score tradeoff.",
      "public_metrics": {
        "win_rate": 0.8722,
        "draw_rate": 0.0588,
        "gate_count": 80,
        "circuit_depth": 27,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0007",
      "parent_id": "p0005",
      "generation": 37,
      "island_idx": 0,
      "combined_score": 0.91,
      "correct": 1,
      "children_count": 3,
      "timestamp": "2026-07-13T21:06:00Z",
      "complexity": 80,
      "patch_name": "Add data re-uploading to third layer",
      "patch_description": "Extended the re-uploading pattern introduced at generation 33 to a third block, re-encoding board state one more time before the final measurement layer.",
      "patch_type": "insertion",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Marginal gain, within noise of the eval harness. Diminishing returns from further re-uploading depth on this board size.",
      "public_metrics": {
        "win_rate": 0.8674,
        "draw_rate": 0.0374,
        "gate_count": 80,
        "circuit_depth": 27,
        "param_count": 5
      },
      "code_diff": "@@ -14,7 +14,21 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for layer in range(2):\n+        for q in range(n_qubits):\n+            qc.rz(params[n_qubits + q + layer * n_qubits], q)\n+        for i in range(n_qubits):\n+            for j in range(i + 1, n_qubits):\n+                qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for layer in range(2):\n        for q in range(n_qubits):\n            qc.rz(params[n_qubits + q + layer * n_qubits], q)\n        for i in range(n_qubits):\n            for j in range(i + 1, n_qubits):\n                qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0008",
      "parent_id": "p0005",
      "generation": 36,
      "island_idx": 0,
      "combined_score": 0.72,
      "correct": 0,
      "children_count": 2,
      "timestamp": "2026-07-13T20:44:00Z",
      "complexity": 86,
      "patch_name": "Try 4-layer re-uploading (regression)",
      "patch_description": "Attempted to push re-uploading depth to 4 layers in one step rather than incrementally. Circuit compiled but the classical optimizer failed to converge within the iteration budget.",
      "patch_type": "mutation",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Optimizer did not converge; final params look close to the random-init distribution. Marked incorrect by the harness because the returned circuit fails the measurement-shape contract check (wrong number of classical bits wired). Reverting to the generation-33 depth is recommended.",
      "public_metrics": {
        "win_rate": 0.6912,
        "draw_rate": 0.0278,
        "gate_count": 86,
        "circuit_depth": 30,
        "param_count": 4
      },
      "code_diff": "@@ -14,7 +14,21 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for layer in range(2):\n+        for q in range(n_qubits):\n+            qc.rz(params[n_qubits + q + layer * n_qubits], q)\n+        for i in range(n_qubits):\n+            for j in range(i + 1, n_qubits):\n+                qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for layer in range(2):\n        for q in range(n_qubits):\n            qc.rz(params[n_qubits + q + layer * n_qubits], q)\n        for i in range(n_qubits):\n            for j in range(i + 1, n_qubits):\n                qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0009",
      "parent_id": "p0006",
      "generation": 39,
      "island_idx": 0,
      "combined_score": 0.92,
      "correct": 1,
      "children_count": 2,
      "timestamp": "2026-07-14T23:43:00Z",
      "complexity": 91,
      "patch_name": "Minor RY param re-init after pruning",
      "patch_description": "Re-initialized the RY layer parameters after the generation-35 pruning pass since removing CZ pairs shifted the loss landscape enough that the old parameter values were no longer near a local optimum.",
      "patch_type": "param_tune",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Slight further improvement and faster convergence in the classical optimizer loop.",
      "public_metrics": {
        "win_rate": 0.88,
        "draw_rate": 0.186,
        "gate_count": 91,
        "circuit_depth": 29,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0010",
      "parent_id": null,
      "generation": 0,
      "island_idx": 1,
      "combined_score": 0.09,
      "correct": 1,
      "children_count": 2,
      "timestamp": "2026-07-01T08:20:00Z",
      "complexity": 13,
      "patch_name": "Seed: all-H + linear CX ansatz",
      "patch_description": "Same baseline hardware-efficient seed program as island 0, run independently so the two islands can diverge under separate selection pressure.",
      "patch_type": "insertion",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Baseline performance, comparable to island 0's root.",
      "public_metrics": {
        "win_rate": 0.0635,
        "draw_rate": 0.1332,
        "gate_count": 13,
        "circuit_depth": 5,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0011",
      "parent_id": "p0010",
      "generation": 3,
      "island_idx": 1,
      "combined_score": 0.13,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-02T11:36:00Z",
      "complexity": 20,
      "patch_name": "Add barrier + measurement reorder",
      "patch_description": "Cosmetic-adjacent patch: inserted a barrier before measurement and reordered classical bit assignment to match board indexing convention used elsewhere in the codebase.",
      "patch_type": "refactor",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "No real score change; mostly a correctness/readability patch that the LLM proposed after noticing an indexing mismatch in the text feedback from generation 0.",
      "public_metrics": {
        "win_rate": 0.0954,
        "draw_rate": 0.0325,
        "gate_count": 20,
        "circuit_depth": 6,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0012",
      "parent_id": "p0011",
      "generation": 8,
      "island_idx": 1,
      "combined_score": 0.19,
      "correct": 1,
      "children_count": 2,
      "timestamp": "2026-07-03T16:58:00Z",
      "complexity": 25,
      "patch_name": "Add second qubit pair CX",
      "patch_description": "Added one extra CX between qubits 0 and 2 on top of the linear chain, giving a partial triangle topology without going fully dense.",
      "patch_type": "mutation",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Small improvement, in line with island 0's early trajectory but slower.",
      "public_metrics": {
        "win_rate": 0.2188,
        "draw_rate": 0.174,
        "gate_count": 25,
        "circuit_depth": 7,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0013",
      "parent_id": "p0012",
      "generation": 8,
      "island_idx": 1,
      "combined_score": 0.1,
      "correct": 0,
      "children_count": 1,
      "timestamp": "2026-07-03T16:48:00Z",
      "complexity": 27,
      "patch_name": "Randomize entangling gate order",
      "patch_description": "Randomly permuted the order CX gates are applied in, hypothesizing that order might matter for the optimizer's initial gradient landscape.",
      "patch_type": "mutation",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "No measurable effect on score, but a transpilation bug in this variant produces a circuit with a dangling unmeasured ancilla under certain qubit counts; harness flags as incorrect.",
      "public_metrics": {
        "win_rate": 0.0722,
        "draw_rate": 0.1344,
        "gate_count": 27,
        "circuit_depth": 10,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0014",
      "parent_id": "p0012",
      "generation": 14,
      "island_idx": 1,
      "combined_score": 0.24,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-05T22:01:00Z",
      "complexity": 35,
      "patch_name": "Ring entanglement (independent discovery)",
      "patch_description": "Island 1 independently converges on the same ring-topology idea island 0 found at generation 11, arrived at via a differently-worded LLM prompt about symmetry.",
      "patch_type": "refactor",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Comparable gain to island 0's equivalent patch, supporting that this is a genuinely useful structural change rather than a fluke of one island's random seed.",
      "public_metrics": {
        "win_rate": 0.2196,
        "draw_rate": 0.0577,
        "gate_count": 35,
        "circuit_depth": 12,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": "q0: --H--@--------------RY(t0)--Z--\nq1: --H--X--@-----------RY(t1)--Z--\nq2: --H-----X--@--------RY(t2)--Z--\n"
    },
    {
      "id": "p0015",
      "parent_id": "p0014",
      "generation": 21,
      "island_idx": 1,
      "combined_score": 0.3,
      "correct": 1,
      "children_count": 2,
      "timestamp": "2026-07-08T05:46:00Z",
      "complexity": 48,
      "patch_name": "Two RY layers, shared params",
      "patch_description": "Added a second RY layer but tied its parameters to the first layer (parameter sharing) instead of introducing new free parameters, to keep the optimizer's search space small.",
      "patch_type": "param_tune",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Modest gain with no extra parameter-count cost, a nice complexity/score tradeoff for this island's more conservative search trajectory.",
      "public_metrics": {
        "win_rate": 0.2987,
        "draw_rate": 0.0508,
        "gate_count": 48,
        "circuit_depth": 16,
        "param_count": 4
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0016",
      "parent_id": "p0015",
      "generation": 28,
      "island_idx": 1,
      "combined_score": 0.33,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-10T12:51:00Z",
      "complexity": 63,
      "patch_name": "Prune to essential CX only",
      "patch_description": "Removed the wrap-around CX in the ring, reverting partially toward linear connectivity after profiling showed the wrap-around pair had low sensitivity for this island's trained parameters.",
      "patch_type": "pruning",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Score roughly flat, gate count down. A defensible complexity trade but this island has not found island 0's full-connectivity + re-uploading combination yet.",
      "public_metrics": {
        "win_rate": 0.317,
        "draw_rate": 0.0686,
        "gate_count": 63,
        "circuit_depth": 21,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0017",
      "parent_id": "p0015",
      "generation": 30,
      "island_idx": 1,
      "combined_score": 0.36,
      "correct": 1,
      "children_count": 3,
      "timestamp": "2026-07-11T14:06:00Z",
      "complexity": 70,
      "patch_name": "Full connectivity, no re-uploading",
      "patch_description": "Tried island 0's full CZ ladder idea (visible to this island via the shared program archive) but without the data re-uploading component.",
      "patch_type": "crossover",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Improvement, but noticeably smaller than island 0's combined patch: about a third of the score jump, suggesting re-uploading and full connectivity are complementary rather than redundant.",
      "public_metrics": {
        "win_rate": 0.3774,
        "draw_rate": 0.1597,
        "gate_count": 70,
        "circuit_depth": 23,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0018",
      "parent_id": "p0017",
      "generation": 34,
      "island_idx": 1,
      "combined_score": 0.44,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-12T18:38:00Z",
      "complexity": 73,
      "patch_name": "Add single re-uploading block",
      "patch_description": "Added one data re-uploading block on top of generation 30's full-connectivity ladder, catching up toward island 0's approach one generation after the island-0 jump was recorded in the shared archive.",
      "patch_type": "insertion",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Solid gain, closing much of the gap to island 0, though still behind since this island hasn't done the pruning + param re-init follow-up patches yet.",
      "public_metrics": {
        "win_rate": 0.4544,
        "draw_rate": 0.0922,
        "gate_count": 73,
        "circuit_depth": 23,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,21 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for layer in range(2):\n+        for q in range(n_qubits):\n+            qc.rz(params[n_qubits + q + layer * n_qubits], q)\n+        for i in range(n_qubits):\n+            for j in range(i + 1, n_qubits):\n+                qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for layer in range(2):\n        for q in range(n_qubits):\n            qc.rz(params[n_qubits + q + layer * n_qubits], q)\n        for i in range(n_qubits):\n            for j in range(i + 1, n_qubits):\n                qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0019",
      "parent_id": "p0018",
      "generation": 38,
      "island_idx": 1,
      "combined_score": 0.47,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-13T22:48:00Z",
      "complexity": 84,
      "patch_name": "Second re-uploading block",
      "patch_description": "Extended re-uploading to two blocks, mirroring island 0's generation-33 patch shape.",
      "patch_type": "insertion",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Continued gain, this island is converging toward island 0's solution a few generations behind, a nice illustration of cross-island information flow through the shared archive.",
      "public_metrics": {
        "win_rate": 0.4931,
        "draw_rate": 0.1221,
        "gate_count": 84,
        "circuit_depth": 29,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,21 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for layer in range(2):\n+        for q in range(n_qubits):\n+            qc.rz(params[n_qubits + q + layer * n_qubits], q)\n+        for i in range(n_qubits):\n+            for j in range(i + 1, n_qubits):\n+                qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for layer in range(2):\n        for q in range(n_qubits):\n            qc.rz(params[n_qubits + q + layer * n_qubits], q)\n        for i in range(n_qubits):\n            for j in range(i + 1, n_qubits):\n                qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0020",
      "parent_id": "p0016",
      "generation": 32,
      "island_idx": 1,
      "combined_score": 0.31,
      "correct": 0,
      "children_count": 1,
      "timestamp": "2026-07-11T16:41:00Z",
      "complexity": 72,
      "patch_name": "Aggressive pruning (over-pruned)",
      "patch_description": "Continued pruning from generation 28, removing two more CX gates based on a sensitivity threshold that turned out to be too aggressive for this parameter regime.",
      "patch_type": "pruning",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Circuit no longer has enough entanglement to pass the harness's minimum-expressivity check; flagged incorrect. A cautionary branch showing pruning can overshoot.",
      "public_metrics": {
        "win_rate": 0.3124,
        "draw_rate": 0.0912,
        "gate_count": 72,
        "circuit_depth": 26,
        "param_count": 5
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0021",
      "parent_id": "p0020",
      "generation": 40,
      "island_idx": 1,
      "combined_score": 0.29,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-14T00:35:00Z",
      "complexity": 87,
      "patch_name": "Restore one pruned CX",
      "patch_description": "Walked back one of the two CX removals from generation 32 after the harness flagged the previous variant as incorrect, restoring minimum viable entanglement.",
      "patch_type": "bugfix",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Back to a correct, if unremarkable, program. This branch of island 1 did not recover the score lost to over-pruning within the run's remaining budget.",
      "public_metrics": {
        "win_rate": 0.2612,
        "draw_rate": 0.0644,
        "gate_count": 87,
        "circuit_depth": 30,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0022",
      "parent_id": "p0013",
      "generation": 12,
      "island_idx": 1,
      "combined_score": 0.14,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-05T20:27:00Z",
      "complexity": 38,
      "patch_name": "Fix dangling ancilla bug",
      "patch_description": "Fixed the dangling unmeasured ancilla bug flagged in generation 8's feedback by adding an explicit measurement for all qubits regardless of the parametrized qubit count.",
      "patch_type": "bugfix",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Correctness restored; score is back near where the branch would have been without the regression.",
      "public_metrics": {
        "win_rate": 0.1243,
        "draw_rate": 0.125,
        "gate_count": 38,
        "circuit_depth": 13,
        "param_count": 5
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0023",
      "parent_id": "p0019",
      "generation": 39,
      "island_idx": 1,
      "combined_score": 0.4659,
      "correct": 0,
      "children_count": 0,
      "timestamp": "2026-07-14T23:03:00Z",
      "complexity": 85,
      "patch_name": "Widen RY search range",
      "patch_description": "Auxiliary exploratory patch (widen ry search range) branched from p0019 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "param_tune",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.4661,
        "draw_rate": 0.1626,
        "gate_count": 85,
        "circuit_depth": 30,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0024",
      "parent_id": "p0000",
      "generation": 1,
      "island_idx": 0,
      "combined_score": 0.0946,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-01T09:08:00Z",
      "complexity": 11,
      "patch_name": "Add classical post-selection",
      "patch_description": "Auxiliary exploratory patch (add classical post-selection) branched from p0000 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "insertion",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.1223,
        "draw_rate": 0.1749,
        "gate_count": 11,
        "circuit_depth": 2,
        "param_count": 4
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0025",
      "parent_id": "p0010",
      "generation": 3,
      "island_idx": 1,
      "combined_score": 0.0503,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-02T11:38:00Z",
      "complexity": 16,
      "patch_name": "Simplify measurement basis",
      "patch_description": "Auxiliary exploratory patch (simplify measurement basis) branched from p0010 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "refactor",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.0092,
        "draw_rate": 0.0983,
        "gate_count": 16,
        "circuit_depth": 7,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0026",
      "parent_id": "p0007",
      "generation": 40,
      "island_idx": 0,
      "combined_score": 0.9388,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-14T00:52:00Z",
      "complexity": 93,
      "patch_name": "Retry with different optimizer seed",
      "patch_description": "Auxiliary exploratory patch (retry with different optimizer seed) branched from p0007 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "mutation",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.9618,
        "draw_rate": 0.1767,
        "gate_count": 93,
        "circuit_depth": 32,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0027",
      "parent_id": "p0026",
      "generation": 40,
      "island_idx": 0,
      "combined_score": 0.9067,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-14T00:42:00Z",
      "complexity": 93,
      "patch_name": "Merge two candidate islands' entanglers",
      "patch_description": "Auxiliary exploratory patch (merge two candidate islands' entanglers) branched from p0026 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "crossover",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.9302,
        "draw_rate": 0.1278,
        "gate_count": 93,
        "circuit_depth": 33,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0028",
      "parent_id": "p0007",
      "generation": 38,
      "island_idx": 0,
      "combined_score": 0.9436,
      "correct": 1,
      "children_count": 1,
      "timestamp": "2026-07-13T22:17:00Z",
      "complexity": 81,
      "patch_name": "Try RX instead of RY final layer",
      "patch_description": "Auxiliary exploratory patch (try rx instead of ry final layer) branched from p0007 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "mutation",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.9129,
        "draw_rate": 0.1221,
        "gate_count": 81,
        "circuit_depth": 26,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0029",
      "parent_id": "p0009",
      "generation": 40,
      "island_idx": 0,
      "combined_score": 0.9137,
      "correct": 0,
      "children_count": 0,
      "timestamp": "2026-07-14T00:35:00Z",
      "complexity": 87,
      "patch_name": "Add mid-circuit reset experiment",
      "patch_description": "Auxiliary exploratory patch (add mid-circuit reset experiment) branched from p0009 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "insertion",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.9165,
        "draw_rate": 0.1904,
        "gate_count": 87,
        "circuit_depth": 29,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0030",
      "parent_id": "p0017",
      "generation": 33,
      "island_idx": 1,
      "combined_score": 0.3885,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-12T17:58:00Z",
      "complexity": 74,
      "patch_name": "Reduce shot count for faster eval",
      "patch_description": "Auxiliary exploratory patch (reduce shot count for faster eval) branched from p0017 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "param_tune",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.3956,
        "draw_rate": 0.0918,
        "gate_count": 74,
        "circuit_depth": 25,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0031",
      "parent_id": "p0024",
      "generation": 4,
      "island_idx": 0,
      "combined_score": 0.0852,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-02T12:51:00Z",
      "complexity": 13,
      "patch_name": "Symmetrize parameter initialization",
      "patch_description": "Auxiliary exploratory patch (symmetrize parameter initialization) branched from p0024 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "param_tune",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.0823,
        "draw_rate": 0.0614,
        "gate_count": 13,
        "circuit_depth": 4,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0032",
      "parent_id": "p0007",
      "generation": 38,
      "island_idx": 0,
      "combined_score": 0.9237,
      "correct": 0,
      "children_count": 0,
      "timestamp": "2026-07-13T22:32:00Z",
      "complexity": 86,
      "patch_name": "Drop redundant barrier ops",
      "patch_description": "Auxiliary exploratory patch (drop redundant barrier ops) branched from p0007 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "pruning",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.8794,
        "draw_rate": 0.0628,
        "gate_count": 86,
        "circuit_depth": 30,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0033",
      "parent_id": "p0006",
      "generation": 38,
      "island_idx": 0,
      "combined_score": 0.8619,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-13T22:44:00Z",
      "complexity": 88,
      "patch_name": "Cross-island entangler merge v2",
      "patch_description": "Auxiliary exploratory patch (cross-island entangler merge v2) branched from p0006 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "crossover",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.8313,
        "draw_rate": 0.1051,
        "gate_count": 88,
        "circuit_depth": 31,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0034",
      "parent_id": "p0006",
      "generation": 36,
      "island_idx": 0,
      "combined_score": 0.8587,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-13T20:12:00Z",
      "complexity": 84,
      "patch_name": "Fix off-by-one in qubit indexing",
      "patch_description": "Auxiliary exploratory patch (fix off-by-one in qubit indexing) branched from p0006 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "bugfix",
      "model_name": "claude-opus-4-1",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.8778,
        "draw_rate": 0.0298,
        "gate_count": 84,
        "circuit_depth": 27,
        "param_count": 4
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0035",
      "parent_id": "p0008",
      "generation": 38,
      "island_idx": 0,
      "combined_score": 0.7355,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-13T22:53:00Z",
      "complexity": 84,
      "patch_name": "Add light L2 param regularization",
      "patch_description": "Auxiliary exploratory patch (add light l2 param regularization) branched from p0008 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "param_tune",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.7008,
        "draw_rate": 0.1008,
        "gate_count": 84,
        "circuit_depth": 30,
        "param_count": 6
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0036",
      "parent_id": "p0022",
      "generation": 14,
      "island_idx": 1,
      "combined_score": 0.1316,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-05T22:31:00Z",
      "complexity": 41,
      "patch_name": "Explore odd-even qubit pairing",
      "patch_description": "Auxiliary exploratory patch (explore odd-even qubit pairing) branched from p0022 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "mutation",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.0895,
        "draw_rate": 0.1374,
        "gate_count": 41,
        "circuit_depth": 12,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0037",
      "parent_id": "p0009",
      "generation": 40,
      "island_idx": 0,
      "combined_score": 0.885,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-14T00:06:00Z",
      "complexity": 85,
      "patch_name": "Refactor gate-count accounting helper",
      "patch_description": "Auxiliary exploratory patch (refactor gate-count accounting helper) branched from p0009 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "refactor",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.8481,
        "draw_rate": 0.0204,
        "gate_count": 85,
        "circuit_depth": 30,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits):\n+        qc.cx(q, (q + 1) % n_qubits)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits):\n        qc.cx(q, (q + 1) % n_qubits)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0038",
      "parent_id": "p0017",
      "generation": 32,
      "island_idx": 1,
      "combined_score": 0.3357,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-11T16:17:00Z",
      "complexity": 76,
      "patch_name": "Second full-connectivity sweep",
      "patch_description": "Auxiliary exploratory patch (second full-connectivity sweep) branched from p0017 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "crossover",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.2981,
        "draw_rate": 0.0734,
        "gate_count": 76,
        "circuit_depth": 24,
        "param_count": 5
      },
      "code_diff": "@@ -14,7 +14,18 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for i in range(n_qubits):\n+        for j in range(i + 1, n_qubits):\n+            qc.cz(i, j)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for i in range(n_qubits):\n        for j in range(i + 1, n_qubits):\n            qc.cz(i, j)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0039",
      "parent_id": "p0028",
      "generation": 40,
      "island_idx": 0,
      "combined_score": 0.9424,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-14T00:13:00Z",
      "complexity": 94,
      "patch_name": "Trim re-uploading to alternating qubits",
      "patch_description": "Auxiliary exploratory patch (trim re-uploading to alternating qubits) branched from p0028 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "pruning",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.9305,
        "draw_rate": 0.1855,
        "gate_count": 94,
        "circuit_depth": 31,
        "param_count": 3
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    },
    {
      "id": "p0040",
      "parent_id": "p0008",
      "generation": 39,
      "island_idx": 0,
      "combined_score": 0.6772,
      "correct": 1,
      "children_count": 0,
      "timestamp": "2026-07-14T23:39:00Z",
      "complexity": 86,
      "patch_name": "Add diagonal CZ shortcut pair",
      "patch_description": "Auxiliary exploratory patch (add diagonal cz shortcut pair) branched from p0008 to probe a nearby region of the search space; included in the sample data to give the tree more branching structure and vary children-count per node.",
      "patch_type": "insertion",
      "model_name": "claude-sonnet-4-5",
      "text_feedback": "Exploratory branch, results roughly in line with the parent program's trajectory.",
      "public_metrics": {
        "win_rate": 0.6595,
        "draw_rate": 0.1895,
        "gate_count": 86,
        "circuit_depth": 28,
        "param_count": 7
      },
      "code_diff": "@@ -14,7 +14,17 @@ def build_ansatz(n_qubits, params):\n-    for q in range(n_qubits - 1):\n-        qc.cx(q, q + 1)\n+    for q in range(n_qubits - 1):\n+        qc.cx(q, q + 1)\n     for q in range(n_qubits):\n         qc.ry(params[q], q)\n",
      "code": "def build_ansatz(n_qubits: int, params: np.ndarray) -> QuantumCircuit:\n    qc = QuantumCircuit(n_qubits)\n    for q in range(n_qubits):\n        qc.h(q)\n    for q in range(n_qubits - 1):\n        qc.cx(q, q + 1)\n    for q in range(n_qubits):\n        qc.ry(params[q], q)\n    qc.measure_all()\n    return qc\n",
      "circuit_svg": null,
      "circuit_text": null
    }
  ]
};
